import React, { useState } from 'react';
import portfolioData from './portfolioData.json';
import './PortfolioGrid.css';

const ProjectCard = ({ title, category, description, techStack }) => (
  <div className="portfolio-card">
      <h3 className="card-title">{title}</h3>
          <span className="card-category">{category}</span>
              <p className="card-description">{description}</p>
                  <div className="tag-container">
                        {techStack.map((tech) => (
                                <span key={tech} className="tech-tag">{tech}</span>
                                      ))}
                                          </div>
                                            </div>
                                            );

                                            const DesignCard = ({ client, service, description, mediaType, mediaPath, onOpenModal }) => (
                                              <div className="portfolio-card design-card">
                                                  <div 
                                                        className="media-container clickable-media" 
                                                              onClick={() => onOpenModal({ mediaType, mediaPath })}
                                                                  >
                                                                        {mediaType === 'video' ? (
                                                                                <video className="design-media" autoPlay loop muted playsInline>
                                                                                          <source src={mediaPath} type="video/mp4" />
                                                                                                  </video>
                                                                                                        ) : (
                                                                                                                <img src={mediaPath} alt={client} className="design-media" />
                                                                                                                      )}
                                                                                                                            <div className="hover-overlay"><span>View Fullscreen</span></div>
                                                                                                                                </div>
                                                                                                                                    <div className="card-content">
                                                                                                                                          <h3 className="card-title">{client}</h3>
                                                                                                                                                <span className="card-category">{service}</span>
                                                                                                                                                      <p className="card-description">{description}</p>
                                                                                                                                                          </div>
                                                                                                                                                            </div>
                                                                                                                                                            );

                                                                                                                                                            const PortfolioGrid = () => {
                                                                                                                                                              const [selectedMedia, setSelectedMedia] = useState(null);

                                                                                                                                                                const closeModal = () => setSelectedMedia(null);

                                                                                                                                                                  return (
                                                                                                                                                                      <div className="portfolio-wrapper">
                                                                                                                                                                            <section className="portfolio-section">
                                                                                                                                                                                    <h2 className="section-header">Development Projects</h2>
                                                                                                                                                                                            <div className="card-grid">
                                                                                                                                                                                                      {portfolioData.projects.map((project) => (
                                                                                                                                                                                                                  <ProjectCard key={project.id} {...project} />
                                                                                                                                                                                                                            ))}
                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                          </section>

                                                                                                                                                                                                                                                <section className="portfolio-section">
                                                                                                                                                                                                                                                        <h2 className="section-header">Client Engagements & Audits</h2>
                                                                                                                                                                                                                                                                <div className="card-grid">
                                                                                                                                                                                                                                                                          {portfolioData.clientWork.map((work) => (
                                                                                                                                                                                                                                                                                      <DesignCard key={work.id} {...work} onOpenModal={setSelectedMedia} />
                                                                                                                                                                                                                                                                                                ))}
                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                              </section>

                                                                                                                                                                                                                                                                                                                    {selectedMedia && (
                                                                                                                                                                                                                                                                                                                            <div className="modal-overlay" onClick={closeModal}>
                                                                                                                                                                                                                                                                                                                                      <div className="modal-content" onClick={(e) => e.stopPropagation()}>
                                                                                                                                                                                                                                                                                                                                                  <button className="close-button" onClick={closeModal}>&times;</button>
                                                                                                                                                                                                                                                                                                                                                              {selectedMedia.mediaType === 'video' ? (
                                                                                                                                                                                                                                                                                                                                                                            <video className="modal-media" controls autoPlay>
                                                                                                                                                                                                                                                                                                                                                                                            <source src={selectedMedia.mediaPath} type="video/mp4" />
                                                                                                                                                                                                                                                                                                                                                                                                          </video>
                                                                                                                                                                                                                                                                                                                                                                                                                      ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                    <img src={selectedMedia.mediaPath} alt="Fullscreen view" className="modal-media" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                              export default PortfolioGrid;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              